/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/views/**/*.ejs"],
  theme: {
    extend: {
      colors: {
        "primary": "#1b6d24",
        "primary-container": "#a3f69c",
        "primary-dim": "#076019",
        "primary-fixed": "#a3f69c",
        "primary-fixed-dim": "#95e88f",
        "on-primary": "#e5ffdd",
        "on-primary-container": "#065f18",
        "on-primary-fixed": "#004b0f",
        "on-primary-fixed-variant": "#176a21",
        "inverse-primary": "#9df197",
        "secondary": "#53616a",
        "secondary-dim": "#47555e",
        "secondary-container": "#d6e5ef",
        "secondary-fixed": "#d6e5ef",
        "secondary-fixed-dim": "#c8d6e1",
        "on-secondary": "#f4faff",
        "on-secondary-container": "#46545d",
        "on-secondary-fixed": "#33414a",
        "on-secondary-fixed-variant": "#4f5d67",
        "tertiary": "#566259",
        "tertiary-dim": "#4a564d",
        "tertiary-container": "#e7f4e8",
        "tertiary-fixed": "#e7f4e8",
        "tertiary-fixed-dim": "#d9e6da",
        "on-tertiary": "#effcf0",
        "on-tertiary-container": "#515d54",
        "on-tertiary-fixed": "#3f4b42",
        "on-tertiary-fixed-variant": "#5b675e",
        "error": "#9e422c",
        "error-dim": "#5c1202",
        "error-container": "#fe8b70",
        "on-error": "#fff7f6",
        "on-error-container": "#742410",
        "surface": "#f4faff",
        "surface-bright": "#f4faff",
        "surface-dim": "#a7e2ff",
        "surface-tint": "#1b6d24",
        "surface-variant": "#bde9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#e7f6ff",
        "surface-container": "#d9f2ff",
        "surface-container-high": "#cbedff",
        "surface-container-highest": "#bde9ff",
        "on-surface": "#003749",
        "on-surface-variant": "#30657b",
        "on-background": "#003749",
        "background": "#f4faff",
        "outline": "#4e8198",
        "outline-variant": "#86b9d2",
        "inverse-surface": "#011017",
        "inverse-on-surface": "#8f9fa9",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
